server:
  port: 19000
  tomcat:
    basedir: ./
    accesslog:
      buffered: false
      directory: logs
      enabled: true
      file-date-format: .yyyy-MM-dd
      pattern: '%h %l %u %t "%r" %s"%{Referer}i" "%{User-Agent}i" %D %{x-request-id}r %{user-id}r %{resource-id}r'
      prefix: access_log
      rename-on-rotate: true
      request-attributes-enabled: false
      rotate: true
      suffix: .log

spring:
  profiles:
    active: dev
  redis:
    mode: single # 单机模式:single 哨兵式:sentinel 集群模式:cluster
    database: 0
    password: whalesharkim
    timeout: 3000 # 超时时间
    poolMinIdle: 4 #最小空闲数
    poolConnTimeout: 3000 # 连接超时时间(秒)
    poolSize: 10 # 连接池大小
    single: #redis单机配置
      address: 127.0.0.1:6379
    redisson:
      config:
        singleServerConfig:
          password: whalesharkim
          address: "redis://127.0.0.1:6379"
          database: 1
        threads: 0
        nettyThreads: 0
        transportMode: "NIO"

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtualHost: /
    userName: admin
    password: admin
    #这个配置是保证提供者确保消息推送到交换机中，不管成不成功，都会回调
    publisher-confirm-type: correlated
    #保证交换机能把消息推送到队列中
    publisher-returns: true
      #这个配置是保证消费者会消费消息，手动确认
      listener:
        simple:
          acknowledge-mode: manual
      template:
        mandatory: true

  zkConfig:
    zkAddr: 127.0.0.1:2181
    zkConnectTimeOut: 5000

im:
  tcpPort: 19001
  webSocketPort: 19002
  bossThreadSize: 1
  workThreadSize: 8
  heartBeatTime: 3000 # 心跳超时时间 单位毫秒
  brokerId: 1001
  logicUrl: http://localhost:18000/v1 # Feign RPC 调用业务层
  loginModel: 3
  # 多端同步模式: 1 只允许一端在线，手机/电脑/web 踢掉除了本 client+imei 的设备
  #             2 允许手机/电脑的一台设备 + web 在线 踢掉除了本 client+imei 的非 web 端设备
  #             3 允许手机和电脑单设备 + web 同时在线 踢掉非本 client+imei 的同端设备
  #             4 允许所有端多设备登录 不踢任何设备

# logger 配置
logging:
  level:
    root: info
    com:
      bantanger:
        im:
          tcp: debug

# 配置全局 httpClient 设置
httpclient:
  maxTotal: 100
  defaultMaxPerRoute: 50
  connectTimeout: 2000
  connectionRequestTimeout: 2000
  socketTimeout: 5000
  staleConnectionCheckEnabled: true