db:
  database: im_register_login_demo
  username: root
  #password: whalesharkim
  password: 123456
  ip: 127.0.0.1:3306

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: ${db.password}
    url: jdbc:mysql://${db.ip}/${db.database}?serverTimezone=UTC&useSSL=false&characterEncoding=UTF8&allowPublicKeyRetrieval=true
    username: ${db.username}

server:
  port: 21000
  tomcat:
    basedir: ./
    accesslog:
      buffered: false
      directory: im-design-demo/im-register-login-demo/login-ordinary-demo/logs
      enabled: true
      file-date-format: .yyyy-MM-dd
      pattern: '%h %l %u %t "%r" %s"%{Referer}i" "%{User-Agent}i" %D %{x-request-id}r %{user-id}r %{resource-id}r'
      prefix: access_log
      rename-on-rotate: true
      request-attributes-enabled: false
      rotate: true
      suffix: .log

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    db-config:
      update-strategy: NOT_EMPTY
  type-aliases-package: com.bantanger.design.ordinary

#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 配置全局 httpClient 设置
httpclient:
  maxTotal: 100
  defaultMaxPerRoute: 50
  connectTimeout: 2000
  connectionRequestTimeout: 2000
  socketTimeout: 5000
  staleConnectionCheckEnabled: true
