DATABASE: im_register_login_demo
USERNAME: root
#password: whalesharkim
PASSWORD: 123456
IP: 127.0.0.1:3306

spring:
#  profiles:
#    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    url: jdbc:mysql://${IP}/${DATABASE}?serverTimezone=UTC&useSSL=false&characterEncoding=UTF8&allowPublicKeyRetrieval=true
    username: root

  application:
    name: im-register-login-bridge-demo

github:
  state: GITHUB
  user_prefix: ${github.state}@

  # ========= 自己申请 client_id\secret 用完之后记得删除 =========
  client_id: 735c33bd4f1fe621bd03
  client_secret: f3b10f7e941f191b8eeaf0595660103181ab647c
  # ==========================================================

  callback: http://localhost:${server.port}/bridge/v1/github # github 回调 callback 会携带 code 参数
  token_url: https://github.com/login/oauth/access_token?client_id=${github.client_id}&client_secret=${github.client_secret}&redirect_uri=${github.callback}&code= # 拼接 code
  user_url: https://api.github.com/user # 使用访问令牌访问 API

  authorize_uri: https://github.com/login/oauth/authorize?client_id=${github.client_id}&redirect_uri=${github.callback}&state=${github.state}

server:
  port: 21002
  tomcat:
    basedir: ./
    accesslog:
      buffered: false
      directory: logs
      enabled: true
      file-date-format: .yyyy-MM-dd
      pattern: '%h %l %u %t "%r" %s"%{Referer}i" "%{User-Agent}i" %D %{x-request-id}r %{user-id}r %{resource-id}r'
      prefix: access_log
      rename-on-rotate: true
      request-attributes-enabled: false
      rotate: true
      suffix: .log

# logger 配置
logging:
  level:
    root: info
    com:
      bantanger:
        im:
          design: debug

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    db-config:
      update-strategy: NOT_EMPTY
  type-aliases-package: com.bantanger.im.design

#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 配置全局 httpClient 设置
httpclient:
  maxTotal: 100
  defaultMaxPerRoute: 50
  connectTimeout: 2000
  connectionRequestTimeout: 2000
  socketTimeout: 5000
  staleConnectionCheckEnabled: true
